// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "description": "login to access your account",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "description": "Register request body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/menu/create-category": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "parameters": [
                    {
                        "description": "Create category request body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CategoryRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/menu/create-menu": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Create menu",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Menu name EN",
                        "name": "menuNameEn",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Menu name LO",
                        "name": "menuNameLo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Category name",
                        "name": "categoryName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Price",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unit",
                        "name": "unit",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Promotion name",
                        "name": "promotionName",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Promotion price",
                        "name": "promotionPrice",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Menu image",
                        "name": "menuImage",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/api/menu/edit-menu/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Edit menu",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Menu ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Menu name EN",
                        "name": "menuNameEn",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Menu name LO",
                        "name": "menuNameLo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Category name",
                        "name": "categoryName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Price",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unit",
                        "name": "unit",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Promotion name",
                        "name": "promotionName",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Promotion price",
                        "name": "promotionPrice",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Menu image (optional, send to replace)",
                        "name": "menuImage",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MenuResponse"
                        }
                    }
                }
            }
        },
        "/api/users/get-profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "models.CategoryRequest": {
            "type": "object",
            "properties": {
                "categoryName": {
                    "type": "string"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.MenuResponse": {
            "type": "object",
            "properties": {
                "categoryName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "menuId": {
                    "type": "string"
                },
                "menuImage": {
                    "type": "string"
                },
                "menuNameEn": {
                    "type": "string"
                },
                "menuNameLo": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "promotionName": {
                    "type": "string"
                },
                "promotionPrice": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.RegisterRequest": {
            "type": "object",
            "properties": {
                "blocked": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "passwordHash": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Lopster POS API",
	Description:      "Lopster POS backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
